CREATE TABLE IF NOT EXISTS tb_user (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	login varchar(255) NOT NULL,
	name varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	profile varchar(255) NULL,
	CONSTRAINT tb_user_pkey PRIMARY KEY (id)
);